const ADD_TO_WATCHLIST = "ADD_TO_WATCHLIST";
const ADD_TO_WATCHED = "ADD_TO_WATCHED";
const REMOVE_FROM_WATCHLIST = "REMOVE_FROM_WATCHLIST";
const REMOVE_FROM_WATCHED = "REMOVE_FROM_WATCHED";

export {
  ADD_TO_WATCHED,
  ADD_TO_WATCHLIST,
  REMOVE_FROM_WATCHED,
  REMOVE_FROM_WATCHLIST,
};
